export const productData = [
    {
      category: 'API Intermediates',
      products: [
        {
          name: 'Pregabalin IP',
          image: '',
          type: 'Other',
          smell: 'Other',
          color: 'Other',
          casNo: '148553-50-8',
          storage: 'Ankleshwar',
          placeOfOrigin: 'Other',
          hsCode: '2942',
          price: '7500',
        },
        {
          name: 'Salbutamol Sulphate',
          image: '',
          casNo: '5593-20-4',
          storage: 'Room Temperature',
          placeOfOrigin: 'India',
          grade: 'Medicine Grade',
          form: 'Powder',
          smell: 'Other',
          purity: 'High',
          price: '7500',
        },
        {
          name: 'Salbutamol IP',
          image: '',
          casNo: '18559-94-9',
          placeOfOrigin: 'Ankleshwar',
          molecularFormula: 'C13H21NO3',
          price: '7500',
        },
        {
            name: '1-Naphthalene Methylamine Hydrochloride Ambroxol HCL81',
            image: '',
            grade: 'Medicine Grade',
            otherNames: '1-Naphthalene Methylamine Hydrochloride Ambroxol HCL81',
            storage: 'Room Temperature',
            placeOfOrigin: 'India',
            purity: 'High',
            supplyAbility: '5000 per Month',
            price: '7500',
        },
        {
          name: 'N-N-Bis 112 -Chloroethlyl11 Amine Hydrochloride',
          image: '',
          supplyAbility: '5000 per Month',
          placeOfOrigin: 'India',
          storage: 'Room Temperature',
          purity: 'High',
          application: 'Pharmaceutical Industry',
          otherNames: 'N,N,Bis 112 -Chloroethlyl11 Amine Hydrochloride',
        },
      ],
    },
    {
      category: 'Bulk Drugs / API',
      products: [
        {
          name: 'Pregabalin IP',
          image: '',
          type: 'Other',
          smell: 'Other',
          color: 'Other',
          casNo: '148553-50-8',
          storage: 'Ankleshwar',
          placeOfOrigin: 'Other',
          hsCode: '2942',
          price: '7500',
        },
        {
          name: 'Salbutamol Sulphate',
          image: '',
          casNo: '5593-20-4',
          storage: 'Room Temperature',
          placeOfOrigin: 'India',
          grade: 'Medicine Grade',
          form: 'Powder',
          smell: 'Other',
          purity: 'High',
          price: '7500',
        },
        {
          name: 'Salbutamol IP',
          image: '',
          casNo: '18559-94-9',
          placeOfOrigin: 'Ankleshwar',
          molecularFormula: 'C13H21NO3',
          price: '7500',
        },
        {
          name: '1-Naphthalene Methylamine Hydrochloride Ambroxol HCL81',
          image: '',
          grade: 'Medicine Grade',
          otherNames: '1-Naphthalene Methylamine Hydrochloride Ambroxol HCL81',
          storage: 'Room Temperature',
          placeOfOrigin: 'India',
          purity: 'High',
          supplyAbility: '5000 per Month',
        },
      ],
    },
  ];
  